# Generated by Django 5.1.3 on 2024-11-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0002_alter_ad_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('can_publish', 'Can publish ads'), ('can_mark_urgent', 'Can mark ads as urgent')]},
        ),
    ]
